apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHhPVEV3TWpjeQpNekExTXpoYUZ3MHpPVEV3TWpjeU16QTFNemhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcnB0bFd2dHEvZTh4WHZGV0JKWUUzTm1Nd1J1clBFUkJub2VWY1oxcmtGK05yZm4yUwpyYkdMZVFxSmRpM1NCckVCNEhzcFNyUDdjSDFhMDRCd2psdWxDZlp2OTNyUG90YmRmSlg2OWtuR2FyOGpXWmRSCm1ZUytIbzlFR3pSNmlFdjRjWHAydzRNVXFTSnFnWmJ0MUxwdlIyUjJsYlFCWkIrRFZxWWdZbGJBaGRDU294RDQKRTRJb21oZWFSTkQzZm81K3pYNGVKaUt3UTR4SkdoQi9hZVltdEJjU2lSTG9PcElKRWhvTlhhQ2xXeG9OWXBkKwpLQlZEREU3RE9uT2hUWnhhQkZ3ZjhjWEF4NlNJMHVnSHVBNXltSE1ZTHB0Y1FHbXlEYW9Yd2xHV0UrYVdiZ1V5CjhVMi9YSkVWaU80dXcvL3BNYjlxWERNNXF4Mm82anVENitycEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFiQnd5ZW5uMno4eVN5cXpELwpXanV5cDJXOW1EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFBVUJqYTdWbkEwZGQrbEpWdldESXA2NXlxUTUwCkwvOG5ZQUN0WXBJQ21kcVhUTjFWL0Zua2JkckFNNy9vOHY3ODlJblM0dUJWNmhJK2JQTUZkUVF2anFRNHQxZ1UKNlYvY3dlWTM5T2lpU2hqRVdJTjFjc2FiUGtTeEszeGtFb29YRGtGSXhqRW1JNjdCREdjWG45QlVmRzR6ckhmSwpsTTF2Zmk3aVRYZDBQak5BUlFjWnZZMzhFY3AvZ3RGdHM2a1R1RG5yWll5eTQrREI1MGRFZjhNUThLUlFHdHY2ClhaVkswK0QxZHNraFdhVTZSU2hRVFN5S2IrU0FLdW1nWHB3ajFvYWtEekhxRjVUV1loQmxidVBpMVppNUhWK0cKcTRBeTNsTndzVytxSnNOZy9xNDF4Q3lXeWlPN0Z6MTdPUitNakZnUWNSOGtNOXBUaE1Gckw0Vnd1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCg==
    server: https://88d49ad1-7e2f-4818-aa1f-be6ecf4d966b.k8s.ondigitalocean.com
  name: hive-prod
contexts:
- context:
    cluster: hive-prod
    namespace: polite
    user: deployer
  name: polite-deployer
current-context: polite-deployer
kind: Config
preferences: {}
users:
- name: deployer
  user:
    token: REDACTED
