apiVersion: apps/v1
kind: Deployment
metadata:
  name: polite
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polite
  template:
    metadata:
      labels:
        app: polite
    spec:
      containers:
      - args:
        - --greeting=howdy
        env:
        - name: PORT
          value: "8080"
        image: gcr.io/TO_BE_DEFINED/polite:fb170a4
        imagePullPolicy: IfNotPresent
        name: polite
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 250M
          requests:
            cpu: 20m
            memory: 55M
      imagePullSecrets:
      - name: gcr-json-key
