apiVersion: apps/v1
kind: Deployment
metadata:
  name: polite
  namespace: staging # TODO: template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polite
  template:
    metadata:
      labels:
        app: polite
    spec:
      imagePullSecrets:
      - name: gcr-json-key # TODO: template this.
      containers:
      - name: polite
        image: gcr.io/k8s-cicd-251209/polite:v2 # TODO: template part of this.
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        args:
          - --greeting=howdy
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "50m"
            memory: "250M"

