steps:

# download dependencies
# SKIP

# run tests
- name: 'gcr.io/cloud-builders/go:alpine'
  id: Run unit tests
  args: ['test', './src/']
  env: ['GOPATH=.']
  # env: ['PROJECT_ROOT=polite']

# bundle app into container image
- name: 'gcr.io/cloud-builders/docker'
  id: Build docker image
  args: [ 'build', '--quiet', '-t', 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA', '.']

# push the image to a registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push image to registry
  args: [ 'push', 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA']

# update the image version in the staging deployment manifest
# NOTE: I don't like the use of regex to update image tag, but no better option yet.
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update deployment image tag for staging
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    sed -E -i "s|image:[[:space:]]*gcr[^[:space:]]*|image: gcr.io/$PROJECT_ID/polite:$SHORT_SHA|g" $_DEPLOYMENT_MANIFEST && \
    cat k8s/staging-deployment.yaml
substitutions:
    _DEPLOYMENT_MANIFEST: k8s/staging-deployment.yaml
images:
- 'gcr.io/$PROJECT_ID/polite'