steps:

- name: 'gcr.io/cloud-builders/go:alpine'
  id: Run unit tests
  args: ['test', './app/src']
  env: ['GOPATH=.']

- name: gcr.io/cloud-builders/docker
  id: Build application image
  args: ['build', '-f', './app/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA', '.']

images:
- 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA'
