steps:

- name: 'gcr.io/cloud-builders/go:alpine'
  id: Run unit tests
  args: ['test', './src/']
  env: ['GOPATH=.']

- name: 'gcr.io/cloud-builders/docker'
  id: Build application image
  args: [ 'build', '--quiet', '-t', 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: Push image to registry
  args: [ 'push', 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA']

- name: 'gcr.io/$PROJECT_ID/go-make-kubectl'
  id: Tool Check
  entrypoint: bash
  args:
  - '-c'
  - |
    which bash
    which make
    echo "--kubectl"
    which kubectl

images:
- 'gcr.io/$PROJECT_ID/polite'
