steps:

- name: 'gcr.io/cloud-builders/go:alpine'
  id: Run unit tests
  args: ['test']
  dir: 'app/src'
  # env: ['GOPATH=.']

- name: gcr.io/cloud-builders/docker
  id: Build application image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA', '.']
  dir: 'app'

images:
- 'gcr.io/$PROJECT_ID/polite:$SHORT_SHA'
