apiVersion: v1
kind: Namespace
metadata:
  name: polite
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  deployer
  namespace: polite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: polite
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: polite
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io